name: BayesTrends
channels:
  - conda-forge
dependencies:
  - cartopy
  - arviz>=0.13.0 # Install with PiP if not available on Anaconda
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - patsy
  - cmdstanpy
  - requests
  - scipy
  - tqdm
  - watermark
  - xarray

